version: '3.8'

services:
  gastrogo-api:
    build: .
    container_name: gastrogo-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://18.117.121.144:27017/GastroGoDB  # Use the MongoDB VM's IP
    networks:
      - gastrogo-net

networks:
  gastrogo-net:
    driver: bridge